# -*- coding: utf-8 -*-
"""Aula 1 processamento de imagens

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOHdZ4cB-8kyv-wFtjglZYI08ANjGA9_
"""

from google.colab import files #importa a imagem
import cv2 #Cv2 openCV
from google.colab.patches import cv2_imshow #exibir a imagem no google colab

arquivos = files.upload()

"""Leitura de imagem

"""

img = cv2.imread("cr7.jpg")
print(img)

img = cv2.imread("cr7.jpg")
cv2_imshow(img)

img_mod = img / 2
cv2_imshow(img_mod)

import numpy as np
img_mod3 = np.minimum(img*2, 255)
cv2_imshow(img_mod3)

# processo de segmentação
img = cv2.imread("cr7.jpg")
B,G,R = cv2.split(img)
cv2_imshow(B)

import matplotlib.pyplot as plt
img = cv2.imread("cr7.jpg")
B, G , R = cv2.split(img)

#Subplot do azul (B)
plt.subplot(1,3,1)
plt.imshow(B)
plt.axis('off')
plt.title("Azul (B)")
#Subplot do vermelho (G)
plt.subplot(1,3,2)
plt.imshow(G)
plt.axis('off')
plt.title("Verde (G)")
#Subplot do vermelho (R)
plt.subplot(1,3,3)
plt.imshow(R)
plt.axis('off')
plt.title("Vermelho (R)")

n = np.arange(0,20)

plt.subplot(2,2,1)
plt.plot(n,np.sin(n))
plt.subplot(2,2,2)
plt.plot(n,np.cos(n))
plt.subplot(2,2,3)
plt.plot(n)
plt.subplot(2,2,4)
plt.plot(n*n)